parameter_vault = {
    "DopplerCooling": {
        "doppler_cooling_duration": 0e-6,
        "doppler_cooling_repump_additional": 0e-6,
        "pre_duration": 0e-6,
        "doppler_cooling_frequency_397": 80e6,
        "doppler_cooling_amplitude_397": 0.0,
        "doppler_cooling_att_397": 0.0,
        "doppler_cooling_frequency_866": 40e6,
        "doppler_cooling_amplitude_866": 0.0,
        "doppler_cooling_att_866": 0.0,
    },
    "DriftTracker": {
        "current_b_field": 4.0,
        "current_line_center": 0.0,
    },
    "Excitation_729": {
        "rabi_excitation_frequency": 0e3,
        "rabi_excitation_amplitude": 1.0,
        "rabi_excitation_att": 0.0,
        "rabi_excitation_phase": 0.0,
        "channel_729": "729G",
        "rabi_excitation_duration": 0e-6,
        "line_selection": "S-1/2D-1/2",
        "single_pass_amplitude": 1.0,
        "single_pass_att": 0.0,
    },
    "IonsOnCamera": {
        "ion_number": 1,
    },
    "LocalSpec": {
        "enable": False,
        "detuning": 0.0,
        "att": 0.0,
        "amp": 1.0,
        "duration": 0e-6,
        "line_selection": "S-1/2D-1/2",
    },
    "MolmerSorensen": {
        "duration": 50e-6,
        "line_selection": "S-1/2D-1/2",
        "line_selection_ion2": "S-1/2D-1/2",
        "due_carrier_enable": False,
        "selection_sideband": "axial_frequency",
        "detuning": 6e3,
        "detuning_carrier_1": 0e3,
        "detuning_carrier_2": 0e3,
        "amp_red": 1.0,
        "att_red": 0.0,
        "amp_blue": 1.0,
        "amp_blue_noise_std": 0.0,
        "att_blue": 0.0,
        "amplitude": 1.0,
        "att": 0.0,
        "amplitude_ion2": 1.0,
        "att_ion2": 0.0,
        "amp_blue_ion2": 1.0,
        "att_blue_ion2": 0.0,
        "amp_red_ion2": 1.0,
        "att_red_ion2": 0.0,
        "analysis_pulse_enable": False,
        "SDDS_enable": False,
        "SDDS_rotate_out": False,
        "rotate_in_with_global": False,
        "shape_profile": 0,
        "bichro_enable": True,
        "analysis_duration": 5e-6,
        "analysis_amplitude": 1.0,
        "analysis_att": 0.0,
        "analysis_amplitude_ion2": 1.0,
        "analysis_att_ion2": 0.0,
        "channel_729": "global",
        "ramsey_duration": 20e-6,
        "override_readout": False,
        "ms_phase": 0.0,
        "phase": 0.0,
        "sp_line1_amp": 1.0,
        "sp_line2_amp": 1.0,
        "sp_line1_att": 0.0,
        "sp_line2_att": 0.0,
        "sp_line1_blue_amp": 1.0,
        "sp_line2_blue_amp": 1.0,
        "sp_line1_blue_att": 0.0,
        "sp_line2_blue_att": 0.0,
        "sp_line1_red_amp": 1.0,
        "sp_line2_red_amp": 1.0,
        "sp_line1_red_att": 0.0,
        "sp_line2_red_att": 0.0,
        "sp_due_enable": False,
        "ac_stark_shift": 0e3,
    },
    "OpticalPumping": {
        "amplitude_729": 1.0,
        "att_729": 0.0,
        "optical_pumping_frequency_854": 30e6,
        "optical_pumping_amplitude_854": 1.0,
        "optical_pumping_att_854": 0.0,
        "line_selection": "S-1/2D+3/2",        
    },
    "OpticalPumpingContinuous": {
        "optical_pumping_continuous_duration": 100e-6,
        "optical_pumping_continuous_repump_additional": 0e-6,
    },
    "RabiFlopping": {
        "line_selection": "S-1/2D-1/2",
        "amplitude_729": 1.0,
        "att_729": 0.0,
        "channel_729": "729G",
        "duration": 5e-6,
        "selection_sideband": "axial_frequency",
        "order": 0,
        "detuning": 0.0,
        "composite_pi_rotation": False,
        "noise": False,
    },
    "Rotation729L1": {
        "amplitude": 1.0,
        "att": 0.0,
        "pi_time": 2e-6,
        "composite_pi_rotation": False,
    },
    "Rotation729G": {
        "amplitude": 1.0,
        "att": 0.0,
        "pi_time": 2e-6,
        "line_selection": "S-1/2D-1/2",
    },
    "SidebandCooling": {
        "line_selection": "S-1/2D-5/2",
        "selection_sideband": "axial_frequency",
        "order": 1,
        "stark_shift": 0e3,
        "channel_729": "729G",
        "amplitude_729": 1.0,
        "att_729": 0.0,
        "duration": 100e-6,
        "frequency_866": 40e6,
        "amplitude_866": 1.0,
        "att_866": 0.0,
        "frequency_854": 20e6,
        "amplitude_854": 1.0,
        "att_854": 0.0,
        "sideband_cooling_cycles": 1,
    },
    "SequentialSBCooling": {
        "enable": False,
        "channel_729": "729G",
        "selection_sideband": "axial_frequency",
        "order": 1,
    },
    "SequentialSBCooling1": {
        "enable": False,
        "channel_729": "729G",
        "selection_sideband": "axial_frequency",
        "order": 1,
    },
    "SequentialSBCooling2": {
        "enable": False,
        "channel_729": "729G",
        "selection_sideband": "axial_frequency",
        "order": 1,
    },
    "StatePreparation": {
        "optical_pumping_enable": False,
        "aux_optical_pumping_enable": False,
        "pulsed_optical_pumping": False,
        "sideband_cooling_enable": False,
        "post_delay": 0e-6,
        "number_of_cycles": 1,
        "pulsed_854_duration": 100e-6,
        "pi_time": 10e-6,
        "channel_729": "729G",
        "pulsed_amplitude": 1.0,
        "pulsed_att": 0.0,
    },
    "StateReadout": {
        "readout_mode": "pmt",
        "repeat_each_measurement": 100,
    },
    "SZX": {
        "one_ion_vaet": False,
        "duration": 10e-6,
        "channel_729": "729G",
        "bichro_enable": False,
        "nu_effective": 0e3,
        "amp_blue": 1.0,
        "amp_red": 1.0,
        "att_blue": 0.0,
        "att_red": 0.0,
        "amplitude": 1.0,
        "local_rabi_amp": 1.0,
        "amplitude_L2": 1.0,
        "att_SP_L2": 0.0,
        "att": 0.0,
        "local_rabi_att": 0.0,
        "sideband_selection": "axial_frequency",
        "line_selection": "S-1/2D-1/2",
        "carrier_detuning": 0e3,
        "carrier_detuning_L1": 0e3,
        "phase": 0.0,
        "AC_stark_local": 0.0,
    },
    "TrapFrequencies": {
        "axial_frequency": 1e6,
        "radial_frequency_1": 2e6,
        "radial_frequency_2": 2.4e6,
    },
}

def get_collections():
    return parameter_vault.keys()

def get_parameter_names(collection):
    return parameter_vault[collection].keys()

def get_parameter(path):
    collection = path[0]
    name = path[1]
    return parameter_vault[collection][name]

def set_parameter(path, value):
    collection = path[0]
    if collection not in get_collections():
        raise Exception(f"collection {collection} does not exist")
    name = path[1]
    if name not in get_parameter_names(collection):
        raise Exception(f"parameter {name} does not exist in collection {collection}")
    parameter_vault[collection][name] = value
